#Environment settings
environment: development

# Site settings
title: Dudevictor GitHub IO
email: jvas.2000@gmail.com
description: "Aspirante a Engenheiro de Computação e formado em Ciências e Tecnologia pela UFRN. Desenvolvedor Java Web na Logique Sistemas."
baseurl: ""
url: "http://dudevictor.github.io"
google_analytics: "UA-74364829-1"
title_image: "https://avatars2.githubusercontent.com/u/13340644?v=3&s=460"
disqus_account: dudevictorgithub
github_repository: https://github.com/dudevictor/dudevictor.github.io
addthis_id: ra-56d8c061351eac81
post_limit: 5
project_limit: 3
author_name: José Victor Alves de Souza
short_name: José Victor
profissao: Web Developer

# Social usernames/URLs
github_username:  dudevictor
linkedin_link: https://br.linkedin.com/in/jvictoralves
google_plus_link: https://plus.google.com/103774151163089217676
stackoverflow_link: http://stackoverflow.com/users/2327056/jose-victor?tab=profile
facebook_username: dudevictor

# Collections
collections:
  projects:
    output: true
  programacao-concorrente:
    output: true
    permalink: projects/programacao-concorrente/:path/

# Default values
defaults:
  - scope:
      type: projects
    values:
      use_math_jax: true

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
permalink: pretty
exclude: [vendor]

# Jekyll  TOC Generator Settings
tocTopTag: h3
contentsLabel: Conteúdo
anchorPrefix: topico-

# Polyglot
languages: ["pt-BR", "en"]
default_lang: "pt-BR"
exclude_from_localization: ["assets", "favicons", "css", "js"]
parallel_localization: true

# Date Formats

date_format:
  pt-BR:
    long: "%d de %B de %Y"
  en:
    long: "%B %d, %Y"

gems: [jekyll-last-modified-at]